src/ControlAreas.Operator.Interface/Models/AreaMovementMap.cs
using System.Collections.Generic;

namespace ControlAreas.Operator.Interface.Models
{
    public class MapPoint
    {
        public double latitude { get; set; }
        public double longitude { get; set; } 
    }
    public class AreaMovementMap
    {
        public List<MapPoint> Points { get; set; }
    }
}

src/ControlAreas.Operator.Interface/Models/MovementModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;

namespace ControlAreas.Operator.Interface.Models
{
    public class ItemList
    {
        [DisplayName("Items")]
        public string[] SelectedItemIds { get; set; }
        public IEnumerable<SelectListItem> Items { get; set; }
    }

    public class VehicleProperty
    {
        public int VehicleId { get; set; }
        public DateTime Time { get; set; }
        public string PlateText { get; set; }
    }

    public class ControlAreaProperty
    {
        public int AreaId { get; set; }
        public DateTime FromTime { get; set; }
        public DateTime ToTime { get; set; }
    }

    public class AreaMovementProperty
    {
        public int VehicleId { get; set; }
    }

    public class MovementModel
    {
        public ItemList Vehicles { get; set; }
        public ItemList Movements { get; set; }
    }
}

src/ControlAreas.Operator.Interface/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlAreas.Operator.Interface.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/ControlAreas.Operator.Interface/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using ControlAreas.Operator.Interface.Models;
using ControlAreas.Operator.Interface.Server;

namespace ControlAreas.Operator.Interface.Controllers
{
    public class AreaController : Controller
    {
        private InteractionManager _interactionManager = new InteractionManager();

        public ActionResult IndexArea()
        {
            return View();
        }

        public JsonResult GetAllControlAreas()
        {
            var areas = _interactionManager.GetAllControlAreas();
            return Json(areas.Select(a => _interactionManager.ControlAreaMapToObjectForJson(a)), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetAreaMap(ControlAreaProperty property)
        {
            var controlAreaMap = _interactionManager.GetControlAreaMapFor(property.AreaId);
            return Json(_interactionManager.ControlAreaMapToObjectForJson(controlAreaMap), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetControlAreaDetails(ControlAreaProperty property)
        {
            var areaMovements = _interactionManager.GetControlAreaMovements(property);
            return Json(areaMovements.Select(m => new
            {
                Id = m.Id,
                Plate = _interactionManager.VehicleToString(m.Vehicle),
                FromTime = _interactionManager.GetEventTime(m.FromEvent),
                ToTime = _interactionManager.GetEventTime(m.ToEvent),
                Visits = _interactionManager.GetHabitatFor((int) m.VehicleId,m.ControlAreaId).VisitNumber
            }), JsonRequestBehavior.AllowGet);
        }
    }
}

src/ControlAreas.Operator.Interface/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/ControlAreas.Operator.Interface/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControlAreas.Dbs.Entities.DbEntities;
using ControlAreas.Operator.Interface.Models;
using ControlAreas.Operator.Interface.Server;
using Newtonsoft.Json;

namespace ControlAreas.Operator.Interface.Controllers
{
    public class VehicleController : Controller
    {
        private InteractionManager _interactionManager = new InteractionManager();

        public ActionResult IndexVehicle()
        {
            return View();
        }

        /*[HttpPost]
        public JsonResult GetVehicles(VehicleProperty property)
        {
            var vehicles = _interactionManager.GetAllVehicles();
            return Json(vehicles.Select(v => new
            {
                Id = v.Id.ToString(),
                Plate = _interactionManager.VehicleToString(v)
            }), JsonRequestBehavior.AllowGet);
        }*/

        [HttpPost]
        public JsonResult GetVehicles(VehicleProperty property)
        {
            var vehicles = _interactionManager.GetVehicleByPlate(property.PlateText);
            return Json(vehicles.Select(v => new
            {
                Id = v.Id.ToString(),
                Plate = _interactionManager.VehicleToString(v)
            }), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetMovementsOnTime(VehicleProperty property)
        {
            var movements = _interactionManager.GetMovementsOnTime(property.VehicleId, property.Time);
            return Json(movements.Select(a => new
            {
                AreaId = a.ControlAreaId.ToString(),
            }), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetHabitatContolAreas(VehicleProperty property)
        {
            //var areas = _interactionManager.GetAreaMovementsFor(VehicleId);
            var areas = _interactionManager.GetHabitatFor(property.VehicleId);
            return Json(areas.Select(a => new
            {
                Id = a.ControlArea.Id.ToString(),
                Visits = a.VisitNumber.ToString()
            }), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetHistoryContolAreas(VehicleProperty property)
        {
            var areas = _interactionManager.GetAreaMovementsFor(property.VehicleId);
            return Json(areas.Select(a => new
            {
                Id = a.ControlAreaId.ToString(),
                FromTime = _interactionManager.GetEventTime(a.FromEvent),
                ToTime = _interactionManager.GetEventTime(a.ToEvent)
            }), JsonRequestBehavior.AllowGet);
        }

        

        [HttpPost]
        public JsonResult GetAreaMap(ControlAreaProperty property)
        {
            var controlAreaMap = _interactionManager.GetControlAreaMapFor(property.AreaId);
            return Json( _interactionManager.ControlAreaMapToObjectForJson(controlAreaMap),JsonRequestBehavior.AllowGet);
        }

        
    }
}

src/ControlAreas.Operator.Interface/Controllers/WantedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControlAreas.Operator.Interface.Models;
using ControlAreas.Operator.Interface.Server;

namespace ControlAreas.Operator.Interface.Controllers
{
    public class WantedController : Controller
    {
        private InteractionManager _interactionManager = new InteractionManager();
        // GET: Wanted
        public ActionResult IndexWanted()
        {
            return View();
        }

        public JsonResult GetAllWantedVehicles()
        {
            var wanted = _interactionManager.GetAllWantedVehicles();
            return Json(wanted.Select(w => new
            {
                Id = w.Id,
                VehicleId = w.VehicleId,
                Plate = _interactionManager.VehicleToString(w.Vehicle),
                Reason = w.Reason
            }), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetLastControlArea(VehicleProperty property)
        {
            var area = _interactionManager.GetLastControlAreaFor(property.VehicleId);
            return Json(_interactionManager.ControlAreaMapToObjectForJson(area), JsonRequestBehavior.AllowGet);
        }
    }
}

src/ControlAreas.Operator.Interface/Views/Area/IndexArea.cshtml
<hr />

<div class="container col-md-4">
    
    <div class="form-group row">
        <a class="btn btn-default btn-block input-xs" onclick="populateAreas()">Отобразить все КО</a>
    </div>
    
    <div class="form-group row">
        <div class="row">
            <div class="col-md-6" >
                <label class="input-xs">С:</label>
                <input id="infoFromTime" type="text" class="form-control form_datetime input-xs" aria-describedby="sizing-addon3">
            </div>

            <div class="col-md-6" >
                <label class="input-xs">По:</label>
                <input id="infoToTime" type="text" class="form-control form_datetime input-xs" aria-describedby="sizing-addon3">
            </div>
        </div>
        
        <div class="row" style="padding-left: 15px; padding-right: 15px">
            <a class="btn btn-default btn-block input-xs" onclick="getControlAreaDetails()">Найти</a>
        </div>
        
    </div>

    <div class="form-group row">
        <label class="input-xs">Транспортные средства:</label>
        <table id="vehicleInCaTable" data-height="150" class="input-xs"></table>
    </div>

    <hr />
</div>

<div class="col-md-8">
    <div id="googleMap" style="width:700px;height:700px;"> </div>
</div>



<script type="text/javascript" src="~/Scripts/area/area.js"></script>

src/ControlAreas.Operator.Interface/Views/Home/Index.cshtml
@{
    ViewBag.Title = "";
}

<div class="jumbotron">
    <h1>Контролируемые области</h1>
    <p class="lead">Решение, которое позволяет определять местонахождение транспортного средства.</p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Работа с транспортными средствами</h2>
        <p>
            Возможность посмотреть историю движения по Контролируемым областям отдельного
            транспортного средства, наиболее часто посещенные области и его текущее местонахождение. 
        </p>
        <p><a class="btn btn-default" href='@Url.Action("IndexVehicle", "Vehicle")'>Транспортные средства &raquo;</a></p>
    </div>
    <div class="col-md-6">
        <h2>Работа с контролируемыми областями</h2>
        <p>
            Возможность просмотреть все существующие контролируемые области, детальный список 
            транспортных средств, находящихся в выбранной области. 
        </p>
        <p><a class="btn btn-default" href='@Url.Action("IndexArea", "Area")'>Контролируемые области &raquo;</a></p>
    </div>
</div>

src/ControlAreas.Operator.Interface/Views/Shared/_Layout.cshtml
@using System
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title Контролируемые области</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <link rel="stylesheet" href="~/Content/bootstrap-table/bootstrap-table.css">
        <link rel="stylesheet" href="~/Content/bootstrap-datetimepicker/bootstrap-datetimepicker.css" />
    </head>
    <body>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Контролируемые области", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Анализ ТС", "IndexVehicle", "Vehicle")</li>
                        <li>@Html.ActionLink("Анализ КО", "IndexArea", "Area")</li>
                        <li>@Html.ActionLink("Оперативный интерес", "IndexWanted", "Wanted")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Димплом Мушиц С.</p>
            </footer>
        </div>

    
        @RenderSection("scripts", required: false)
        <script type="text/javascript" src="~/Scripts/moment-with-locales.min.js"></script>
        <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyC2p-81OxLi4yGWG6NCs5d4HcnR3PqdOvI&sensor=true"></script>
        <script type="text/javascript" src="~/Scripts/common/init.js"></script>
        <script type="text/javascript" src="~/Content/bootstrap-table/bootstrap-table.js"></script>
        <script type="text/javascript" src="~/Content/bootstrap-datetimepicker/bootstrap-datetimepicker.js"></script>
        <script type="text/javascript" src="~/Content/bootstrap-datetimepicker/bootstrap-datetimepicker.ru.js"></script>
        <script type="text/javascript" src="~/Scripts/common/graham_scan.js"></script>
        <script type="text/javascript" src="~/Scripts/common/map_drawing.js"></script>
    </body>
</html>

src/ControlAreas.Operator.Interface/Views/Vehicle/IndexVehicle.cshtml
<hr />

<div class="container col-md-4">
    <div class="form-group row">
        <label for="plateText" class="input-xs">ГРЗ:</label>
        <div class="input-group input-group-sm">
            <input id="plateText" type="text" class="form-control" placeholder="Найти..." aria-describedby="sizing-addon3">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button" onclick="populateVehicle()">Найти</button>
            </span>
        </div>
    </div>
    
    <div class="form-group row">
        <label class="input-xs">Выберите ТС:</label>
        <table id="vehicleTable" data-height="100" class="input-xs"></table>
    </div>
    
    <div class="form-group row">
        <label class="input-xs">КО по времени:</label>
        <div class="input-group input-group-sm">
            <input id="positionTime" type="text" class="form-control form_datetime" aria-describedby="sizing-addon3">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button" onclick="showAreaOnTime()">Найти</button>
            </span>
        </div>
    </div>

    <div class="form-group row">
        <label class="input-xs">История движения:</label>
        <table id="historyTable" data-height="150" class="input-xs"></table>
    </div>

    <div class="form-group row">
        <label class="input-xs">Частота посещения КО:</label>
        <table id="habitatTable" data-height="150" class="input-xs"></table>
    </div>

    <hr />
</div>

<div class="col-md-8">
    <div id="googleMap" style="width:700px;height:700px;"> </div>
</div>



<script type="text/javascript" src="~/Scripts/vehicle/vehicle.js"></script>

src/ControlAreas.Operator.Interface/Views/Wanted/IndexWanted.cshtml
<hr />

<div class="container col-md-4">
    <div class="form-group row">
        <label for="plateText" class="input-xs">ГРЗ:</label>
        <div class="input-group input-group-sm">
            <input id="plateText" type="text" class="form-control" placeholder="Найти..." aria-describedby="sizing-addon3">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button" onclick="populateWanted()">Найти</button>
            </span>
        </div>
    </div>

    <div class="form-group row">
        <a class="btn btn-default btn-block input-xs" onclick="populateWanted()">Отобразить все ГРЗ</a>
    </div>

    <div class="form-group row">
        <label class="input-xs">Оперативный интерес:</label>
        <table id="wantedVehiclesTable" data-height="250" class="input-xs"></table>
    </div>

    <div class="form-group row panel panel-default">
        <div class="panel-heading input-xs">
            <label class="panel-title input-xs" id="panel-title">Данные о ТС</label>
        </div>
        <div class="panel-body">
            ...
        </div>
    </div>

    <hr />
</div>

<div class="col-md-8">
    <div id="googleMap" style="width:700px;height:700px;"> </div>
</div>



<script type="text/javascript" src="~/Scripts/wanted/wanted.js"></script>